default:
  bucket_name: 'databrew.org'
  kwale:
    household:
      s3:
        keys:
          raw: "kwale/raw-form/reconbhouseholdtraining/reconbhouseholdtraining.csv"
          anomaly: "kwale/anomaly/reconbhouseholdtraining/reconbhouseholdtraining.csv"
          clean: "kwale/clean-form/reconbhouseholdtraining/reconbhouseholdtraining.csv"
    registration:
      s3:
        keys:
          raw: "kwale/raw-form/reconaregistrationtraining/reconaregistrationtraining.csv"
          anomaly: "kwale/anomaly/reconaregistrationtraining/reconaregistrationtraining.csv"
          clean: "kwale/clean-form/reconaregistrationtraining/reconaregistrationtraining.csv"
